skip_branch_with_pr: true

image: Visual Studio 2017

configuration: Release

install:
  - choco install gitversion.portable -pre -y
  - cmd: dotnet restore src\SpeakEasy.sln
  - ps: gitversion /l console /output buildserver

dotnet_csproj:
  patch: true
  file: 'src\**\*.csproj'
  version: $(GitVersion_NuGetVersion)
  package_version: $(GitVersion_NuGetVersion)
  assembly_version: $(GitVersion_NuGetVersion)
  file_version: $(GitVersion_NuGetVersion)
  informational_version: $(GitVersion_NuGetVersion)

build:
  parallel: true
  project: src\SpeakEasy.sln
  publish_nuget: true

test_script:
  - ps: .\build\run-tests.ps1

# deploy:
#   provider: NuGet
#   skip_symbols: true
#   api_key:
#     secure: T5DAebGxPV1QtMqIYRQyPYhFr3yfKzlkOB2rtVl8SQkJD7nTLEPBPPtcI8MgbHj3
#   on:
#     appveyor_repo_tag: true
