image: Visual Studio 2017

# environment:
#   nuget_version: '1.0.0'

# version: '$(nuget_version)+{build}'

configuration: Release

install:
  - choco install gitversion.portable -pre -y
  - cmd: dotnet restore src\SpeakEasy.sln
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo

assembly_info:
  patch: false

dotnet_csproj:
  patch: false
  file: 'src\**\*.csproj'
  version: $(GitVersion_NuGetVersion)
  package_version: $(GitVersion_NuGetVersion)

build:
  project: src\SpeakEasy.sln
  publish_nuget: true

test_script:
  - ps: .\build\run-tests.ps1

# deploy:
#   provider: NuGet
#   skip_symbols: true
#   api_key:
#     secure: T5DAebGxPV1QtMqIYRQyPYhFr3yfKzlkOB2rtVl8SQkJD7nTLEPBPPtcI8MgbHj3
#   on:
#     appveyor_repo_tag: true
